sudo:
  false

language:
  ruby

rvm:
  - 2.4.0

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout master

install:
  - make install-rb

script:
  - make test-rb
