sudo:
  false

language:
  node_js

node_js:
  - 8

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout master

install:
  - make install-js

script:
  - make test-js
